# Generated by Django 4.0.5 on 2022-07-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cancion',
            new_name='Canciones',
        ),
        migrations.RenameModel(
            old_name='Cantante',
            new_name='Cantantes',
        ),
        migrations.RenameModel(
            old_name='Disco',
            new_name='Discos',
        ),
        migrations.RenameModel(
            old_name='Genero',
            new_name='Generos',
        ),
    ]
