# Generated by Django 4.0.5 on 2022-07-04 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0002_rename_cancion_canciones_rename_cantante_cantantes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generos',
            old_name='tipo',
            new_name='nombre',
        ),
    ]
