# Generated by Django 4.0.5 on 2022-07-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0003_rename_tipo_generos_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generos',
        ),
    ]
