# Generated by Django 4.0.5 on 2022-07-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0004_delete_generos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Canciones',
            new_name='Clases',
        ),
        migrations.RenameModel(
            old_name='Discos',
            new_name='Contacto',
        ),
        migrations.RenameModel(
            old_name='Cantantes',
            new_name='Nosotros',
        ),
    ]
