# Generated by Django 4.0.5 on 2022-07-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0005_rename_canciones_clases_rename_discos_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clases',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
