# Generated by Django 4.0.5 on 2022-07-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0007_remove_clases_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='texto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
