# Generated by Django 4.0.5 on 2022-07-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0009_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clases',
            name='duracion',
        ),
        migrations.AddField(
            model_name='clases',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clases',
            name='horario',
            field=models.DateTimeField(max_length=30, null=True),
        ),
    ]
