# Generated by Django 4.0.5 on 2022-07-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0012_delete_nosotros_remove_clases_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clases',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
